apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.100.151  # 替换为你的 NFS 服务器地址
    path: /mnt/nfs_share   # 替换为你的 NFS 目录路径
